package Model;
// Generated Dec 5, 2014 5:29:36 PM by Hibernate Tools 4.3.1



/**
 * BookFileType generated by hbm2java
 */
public class BookFileType  implements java.io.Serializable {


     private int bookFileTypeId;
     private Book book;
     private String fileType;
     private String downloadLink;

    public BookFileType() {
    }

    public BookFileType(int bookFileTypeId, Book book, String fileType, String downloadLink) {
       this.bookFileTypeId = bookFileTypeId;
       this.book = book;
       this.fileType = fileType;
       this.downloadLink = downloadLink;
    }
   
    public int getBookFileTypeId() {
        return this.bookFileTypeId;
    }
    
    public void setBookFileTypeId(int bookFileTypeId) {
        this.bookFileTypeId = bookFileTypeId;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    public String getDownloadLink() {
        return this.downloadLink;
    }
    
    public void setDownloadLink(String downloadLink) {
        this.downloadLink = downloadLink;
    }




}


