package Model;
// Generated Dec 5, 2014 6:12:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private String bookUuid;
     private String title;
     private String cover;
     private Date dateAdded;
     private int numCopies;
     private int timesBorrowed;
     private Set authors = new HashSet(0);
     private Set genres = new HashSet(0);
     private Set checkedOutBooks = new HashSet(0);
     private Set reservedBooks = new HashSet(0);
     private Set bookFileTypes = new HashSet(0);

    public Book() {
    }

	
    public Book(String bookUuid, String title, String cover, Date dateAdded, int numCopies, int timesBorrowed) {
        this.bookUuid = bookUuid;
        this.title = title;
        this.cover = cover;
        this.dateAdded = dateAdded;
        this.numCopies = numCopies;
        this.timesBorrowed = timesBorrowed;
    }
    public Book(String bookUuid, String title, String cover, Date dateAdded, int numCopies, int timesBorrowed, Set authors, Set genres, Set checkedOutBooks, Set reservedBooks, Set bookFileTypes) {
       this.bookUuid = bookUuid;
       this.title = title;
       this.cover = cover;
       this.dateAdded = dateAdded;
       this.numCopies = numCopies;
       this.timesBorrowed = timesBorrowed;
       this.authors = authors;
       this.genres = genres;
       this.checkedOutBooks = checkedOutBooks;
       this.reservedBooks = reservedBooks;
       this.bookFileTypes = bookFileTypes;
    }
   
    public String getBookUuid() {
        return this.bookUuid;
    }
    
    public void setBookUuid(String bookUuid) {
        this.bookUuid = bookUuid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getCover() {
        return this.cover;
    }
    
    public void setCover(String cover) {
        this.cover = cover;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public int getNumCopies() {
        return this.numCopies;
    }
    
    public void setNumCopies(int numCopies) {
        this.numCopies = numCopies;
    }
    public int getTimesBorrowed() {
        return this.timesBorrowed;
    }
    
    public void setTimesBorrowed(int timesBorrowed) {
        this.timesBorrowed = timesBorrowed;
    }
    public Set getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set authors) {
        this.authors = authors;
    }
    public Set getGenres() {
        return this.genres;
    }
    
    public void setGenres(Set genres) {
        this.genres = genres;
    }
    public Set getCheckedOutBooks() {
        return this.checkedOutBooks;
    }
    
    public void setCheckedOutBooks(Set checkedOutBooks) {
        this.checkedOutBooks = checkedOutBooks;
    }
    public Set getReservedBooks() {
        return this.reservedBooks;
    }
    
    public void setReservedBooks(Set reservedBooks) {
        this.reservedBooks = reservedBooks;
    }
    public Set getBookFileTypes() {
        return this.bookFileTypes;
    }
    
    public void setBookFileTypes(Set bookFileTypes) {
        this.bookFileTypes = bookFileTypes;
    }




}


