package Model;
// Generated Dec 5, 2014 5:29:36 PM by Hibernate Tools 4.3.1



/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private String personUuid;
     private String email;
     private String password;
     private String firstName;
     private String lastName;
     private boolean isAdmin;
     private RegisteredUser registeredUser;

    public Person() {
    }

	
    public Person(String personUuid, String email, String password, String firstName, String lastName, boolean isAdmin) {
        this.personUuid = personUuid;
        this.email = email;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.isAdmin = isAdmin;
    }
    public Person(String personUuid, String email, String password, String firstName, String lastName, boolean isAdmin, RegisteredUser registeredUser) {
       this.personUuid = personUuid;
       this.email = email;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.isAdmin = isAdmin;
       this.registeredUser = registeredUser;
    }
   
    public String getPersonUuid() {
        return this.personUuid;
    }
    
    public void setPersonUuid(String personUuid) {
        this.personUuid = personUuid;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public RegisteredUser getRegisteredUser() {
        return this.registeredUser;
    }
    
    public void setRegisteredUser(RegisteredUser registeredUser) {
        this.registeredUser = registeredUser;
    }




}


