package Model;
// Generated Dec 5, 2014 5:29:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReservedBook generated by hbm2java
 */
public class ReservedBook  implements java.io.Serializable {


     private int reservedBookId;
     private Book book;
     private RegisteredUser registeredUser;
     private Date reserveDate;

    public ReservedBook() {
    }

    public ReservedBook(int reservedBookId, Book book, RegisteredUser registeredUser, Date reserveDate) {
       this.reservedBookId = reservedBookId;
       this.book = book;
       this.registeredUser = registeredUser;
       this.reserveDate = reserveDate;
    }
   
    public int getReservedBookId() {
        return this.reservedBookId;
    }
    
    public void setReservedBookId(int reservedBookId) {
        this.reservedBookId = reservedBookId;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public RegisteredUser getRegisteredUser() {
        return this.registeredUser;
    }
    
    public void setRegisteredUser(RegisteredUser registeredUser) {
        this.registeredUser = registeredUser;
    }
    public Date getReserveDate() {
        return this.reserveDate;
    }
    
    public void setReserveDate(Date reserveDate) {
        this.reserveDate = reserveDate;
    }




}


